source 'https://rubygems.org'

gem 'sinatra'
gem 'json'
gem 'pry'
gem 'thin'
gem 'pony'
gem 'mini_magick'
gem 'fileutils', '~> 1.0'
#gem 'aescrypt'
gem 'video_thumb'
gem 'cloudinary'
gem 'hex_string', '~> 1.0', '>= 1.0.1'
#gem 'urlcrypt', '~> 0.1.1'
