---
name: site
senha: 12345
email:
head:
  title: Portfolio
  description: Site
  author:
moldura:
  label: Portfolio
  logo:
    label: Portfólio
    link: index.ttt
  menu:
  - label: Portfolio  
  - label: Sobre
  - label: Contato
  footer:
    endereco: Endereço
    social:
      facebook: 
      googleplus: 
      twitter: 
      linkedin: 
    about_resumo: texto    
pages:
  home:
    label:
    img:
    body:
  about:
    label: Sobre
    body1:
    body2:
  portfolio:
    label: Portfolio
    items:  
      - id: '0'
        titulo:
        img: "/img/noimage.png"
        txt: 
        cliente:
        site:
        data:
        servico:
        cat:  
  contact:
    label: Contato
