---
info:
  name: site
  email:
  senha: 1
  title: Portfolio geral
  description: Site portfolio
  author: marcelo magalhaes
navbar:
  backgroundColor: hsl(2, 18%, 72%)
  logo:
    label: novosite
    img:
  menu:
  - portfólio
  - sobre
  - contato
head:
  backgroundColor: hsl(2, 60%, 50%)
  backgroundUrl: "/styleBackgrounds/aurora_burst_lime_green-wallpaper-1440x900.jpg"
  fontColor: hsl(247, 13%, 87%)
  avatar: contas/192/img/avatar.jpg?1486077361
  txt1: Nilzete
  txt2: Esmorfismo
  show:
    avatar: true
    txt1: true
    txt2: true
    txtShadow: true
portfolio:
  label: portfólio
  itemsTags:
  - colheita
  - Legal
  - rosali
  - linda
  - in natura
  - na tigela
  items:
  - id: 192-1483983088597
    titulo: a caminho
    img: contas/192/img/portfolio/192-1483983088597.jpg?decache=0.9348386853923367
    txt: Ggggg
    nome: ''
    site: ''
    data: ''
    servico: ''
    cat: ''
    tags:
    - colheita
    - in natura
    - linda
    cliente: Trt
  - id: 192-1483898003899
    titulo: Do bom
    img: contas/192/img/portfolio/192-1483898003899.jpg?decache=0.9492609702977868
    txt: Caprixo
    nome: ''
    site: ''
    data: ''
    servico: ''
    cat: ''
    tags:
    - colheita
    - Legal
  - id: 192-1483115954127
    titulo: no pé
    img: contas/192/img/portfolio/192-1483115954127.jpg
    txt: uma roza é uma roza e é uma roza
    cliente: fidelis
    site: ofidelito.com
    data: 10/10/10
    servico: todos :(
    tags:
    - colheita
    - rosali
    - linda
  - id: 192-1483977341960
    titulo: açai2
    img: contas/192/img/portfolio/192-1483977341960.jpg?decache=0.25454610040371484
    txt: Fggg
    nome: ''
    site:
    data:
    servico:
    cat: ''
    tags:
    - in natura
    cliente:
  - id: 192-1483898166846
    titulo: na Tijela
    img: contas/192/img/portfolio/192-1483898166846.jpg?decache=0.4983468929524648
    txt: ''
    nome: ''
    site: ''
    data: ''
    servico: ''
    cat: ''
    tags:
    - na tigela
  - id: 192-456
    titulo: Bem acompanhado
    img: contas/192/img/portfolio/192-456.jpg?decache=0.1961780816568468
    txt: Super t até 12
    cliente: fff
    site:
    data:
    servico:
    tags:
    - na tigela
about:
  label: sobre
  body1: super textossdsd fdgygvt
  body2: estão aqui ssvvg tvfgggg
contact:
  label: contato
footer:
  endereco:
  social:
    facebook: sdsds
    googleplus: '222'
    twitter: '333'
    linkedin: '444'
  about_resumo: tudo a ver com tudo
