---
name: site
senha: 12345
email:
head:
  title: Portfólio
  description:
  author:
moldura:
  label: Portfolio
  logo:
    label:  
  menu:
  - label: Portfólio  
  - label: Sobre
  - label: Contato
  footer:
    endereco:
    social:
      facebook: 
      googleplus: 
      twitter: 
      linkedin: 
    about_resumo:    
pages:
  home:
    label:
    img:
    body:
  about:
    label: Sobre
    body1:
    body2:
  portfolio:
    label: Portfólio
    items:  
      - id: '0'
        titulo:
        img: "/img/cabin.png"
        txt: 
        cliente:
        site:
        data:
        servico:
        cat:  
  contact:
    label: Contato
