---
info:
  name: site
  email: contato@magaweb.com.br
  senha: 1
  title: Portf贸lio geral
  description: Site portf贸lio
  author: Radiando
navbar:
  backgroundColor: hsl(2, 18%, 72%)
  logo:
    label: novo site
    img:
  menu:
    - portf贸lio
    - sobre
    - contato
head:
  backgroundColor: hsl(168, 77%, 42%)
  backgroundUrl:
  fontColor: hsl(0, 0%, 100%)
  avatar: contas/192/img/avatar.jpg?1486077361
  txt1:
  txt2:
  show:
    avatar: true
    txt1: true
    txt2: true
    txtShadow: false
portfolio:
  label: portf贸lio
  itemsTags:
  items:
  hide: false
about:
  label: sobre
  body1:
  body2:
  hide: false
contact:
  show: true
  label: contato
  hide: false
footer:
  show: true
  endereco:
  social:
    facebook:
    googleplus:
    twitter:
    linkedin:
  about_resumo:
  hide: false
